

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_customerWindow(object):
    def setupUi(self, customerWindow):
        customerWindow.setObjectName("customerWindow")
        customerWindow.resize(1200, 800)
        customerWindow.setMinimumSize(QtCore.QSize(1200, 800))
        customerWindow.setMaximumSize(QtCore.QSize(1200, 800))
        self.tableWidget = QtWidgets.QTableWidget(customerWindow)
        self.tableWidget.setGeometry(QtCore.QRect(300, 110, 891, 541))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(customerWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 110, 291, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.billButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.billButton.setFont(font)
        self.billButton.setObjectName("billButton")
        self.verticalLayout.addWidget(self.billButton)
        self.transactionButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.transactionButton.setFont(font)
        self.transactionButton.setObjectName("transactionButton")
        self.verticalLayout.addWidget(self.transactionButton)
        self.payButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.payButton.setFont(font)
        self.payButton.setObjectName("payButton")
        self.verticalLayout.addWidget(self.payButton)
        self.pushButton_4 = QtWidgets.QPushButton(customerWindow)
        self.pushButton_4.setGeometry(QtCore.QRect(1108, 0, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit = QtWidgets.QTextEdit(customerWindow)
        self.textEdit.setGeometry(QtCore.QRect(430, 70, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(customerWindow)
        self.label.setGeometry(QtCore.QRect(330, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.payButton_2 = QtWidgets.QPushButton(customerWindow)
        self.payButton_2.setGeometry(QtCore.QRect(600, 680, 289, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.payButton_2.setFont(font)
        self.payButton_2.setObjectName("payButton_2")

        self.retranslateUi(customerWindow)
        QtCore.QMetaObject.connectSlotsByName(customerWindow)

    def retranslateUi(self, customerWindow):
        _translate = QtCore.QCoreApplication.translate
        customerWindow.setWindowTitle(_translate("customerWindow", "Form"))
        self.billButton.setText(_translate("customerWindow", "Bill Check"))
        self.transactionButton.setText(_translate("customerWindow", "Transaction Check"))
        self.payButton.setText(_translate("customerWindow", "Pay"))
        self.pushButton_4.setText(_translate("customerWindow", "exit"))
        self.label.setText(_translate("customerWindow", "Search"))
        self.payButton_2.setText(_translate("customerWindow", "Pay"))
