
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(1200, 800)
        loginWindow.setMinimumSize(QtCore.QSize(1200, 800))
        loginWindow.setMaximumSize(QtCore.QSize(1200, 800))
        self.textEdit = QtWidgets.QTextEdit(loginWindow)
        self.textEdit.setGeometry(QtCore.QRect(450, 390, 371, 71))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(loginWindow)
        self.textEdit_2.setGeometry(QtCore.QRect(450, 510, 371, 71))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(loginWindow)
        self.label.setGeometry(QtCore.QRect(290, 400, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(loginWindow)
        self.label_2.setGeometry(QtCore.QRect(290, 520, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(loginWindow)
        self.pushButton.setGeometry(QtCore.QRect(560, 700, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(loginWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 620, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(loginWindow)
        self.pushButton_4.setGeometry(QtCore.QRect(1108, 0, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Form"))
        self.label.setText(_translate("loginWindow", "username"))
        self.label_2.setText(_translate("loginWindow", "password"))
        self.pushButton.setText(_translate("loginWindow", "Register"))
        self.pushButton_2.setText(_translate("loginWindow", "LogIn"))
        self.pushButton_4.setText(_translate("loginWindow", "exit"))
